#mybatis-plus:
#  configuration:
#    default-enum-type-handler: org.cqq.openlibrary.common.presistent.mybatis.typehandler.EnumTypeHandler
#  type-handlers-package: org.cqq.openlibrary.common.presistent.mybatis.typehandler